### ISSUE TITLE
"fileupload is not a function" (icon upload not possible)

### ISSUE THREAD

**Issue by stylefieber** [nextcloud/external#227]
Current version of this extension with Nextcloud 20:

If you open the page in settings the js error occurs in console:

"admin.js:375 Uncaught TypeError: $(...).fileupload is not a function
    at HTMLDocument.<anonymous> (admin.js:375)
    at l (jquery.js:3187)
    at Object.add [as done] (jquery.js:3246)
    at e.fn.init.m.fn.ready (jquery.js:3496)
    at Module.<anonymous> (admin.js:350)
    at n (bootstrap:19)
    at bootstrap:83
    at admin.js?v=8f93d203-10:1"

Might be due to lack of jquery?

Icon upload is not possible because of that.

**Comment by dtony** [comment]
I am facing the same problem, the upload image upload function is not working properly with Nextcloud 20.0.3.

**Comment by nickvergessen** [comment]
Even works fine with 21 beta1 here.

Can you post the list of apps you are running?

**Comment by dtony** [comment]
Sure, I am using the docker image of Nextcloud FYI
``` 
$ occ app:list
Enabled:
  - accessibility: 1.6.0
  - apporder: 0.11.0
  - bookmarks: 4.0.5
  - bruteforcesettings: 2.0.1
  - calendar: 2.1.2
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.4.2
  - contactsinteraction: 1.1.0
  - dav: 1.16.1
  - external: 3.7.1
  - federatedfilesharing: 1.10.1
  - federation: 1.10.1
  - files: 1.15.0
  - files_external: 1.11.1
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.0
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - nextcloud_announcements: 1.9.0
  - notes: 4.0.1
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - ocsms: 2.1.8
  - onlyoffice: 6.2.0
  - password_policy: 1.10.1
  - photos: 1.2.1
  - polls: 1.6.2
  - previewgenerator: 3.0.1
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - viewer: 1.4.0
  - workflowengine: 2.2.0
Disabled:
  - activity
  - admin_audit
  - dashboard
  - encryption
  - user_ldap
  - user_status
  - weather_status```

**Comment by DrSebastianPauli** [comment]
Same here. I'm using NC 20.0.4. First the upload was fine. Then I modified the design of icon (svg) and uploaded the file with the same name again and again. After the third upload, all uploads fail without a message... Hope my description helps a bit.

**Comment by srebrny** [comment]
Witn Nextcloud 20.0.3
 is same situation - information only in console logs

**Comment by ramon-roca** [comment]
Reproducing on chrome 87.0.4280.14 64 bits at 20.0.4 and persists after upgrade to 20.0.5
Icon is not being loaded after picking an image at the browser.
Nothing at nextcloud.log, but got "fileupload is not a function" at the browser javascript console:
`Uncaught TypeError: $(...).fileupload is not a function
    at HTMLDocument.<anonymous> (admin.js:375)
    at l (jquery.js:3187)
    at Object.add [as done] (jquery.js:3246)
    at e.fn.init.m.fn.ready (jquery.js:3496)
    at Module.<anonymous> (admin.js:350)
    at n (bootstrap:19)
    at bootstrap:83
    at admin.js?v=e011207b-38:1`
    
   Firefox 64.0.2 64bit is able to upload the icon.

**Comment by nickvergessen** [comment]
Thanks for mentioning the Chrome vs. Firefox difference.
I was now able to reproduce it, it only happens in Chrome/Chromium based browsers
